/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GroupEditingModal: typeof import('./src/components/GroupEditingModal.vue')['default']
    GroupList: typeof import('./src/components/GroupList.vue')['default']
    MapEditingModal: typeof import('./src/components/MapEditingModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
